console.log("Primeira linha \nSegunda linha")
console.log("Meu nome é 'Talles'")
console.log('O nome dela é "Amanda"')
console.log(`A multiplicação de 5 X 3 é igual a ${5*3}`)
console.log("O " + "meu " + "nome " + "é " + "Talles.")